DOMAIN_TEMPLATES = {
    "tech_startup": [
        "Cover slide — startup name, tagline, founders.",
        "Vision — what future you want to build.",
        "Problem — the pain point and who faces it.",
        "Current gap — why existing solutions are weak.",
        "Solution — your product and unique value.",
        "Product demo — screenshots, workflow, prototype, or architecture.",
        "Market opportunity — TAM, SAM, SOM, and why now.",
        "Business model — pricing and revenue streams.",
        "Competition — rivals and your differentiation.",
        "Traction — users, pilots, revenue, waitlist, or partnerships.",
        "Roadmap / milestones — past progress and next steps.",
        "Team — founders, skills, and credibility.",
        "Funding ask — how much, for what, and expected outcomes."
    ],
    "healthcare": [
        "Cover slide — Brand name and healthcare mission.",
        "The Clinical Need — The specific health problem or patient pain point.",
        "Impact — How it affects patients, providers, or the healthcare system.",
        "Solution — Your medical device, drug, or digital health product.",
        "Clinical Validation — Evidence, trials, and regulatory pathway (FDA, CE).",
        "Business Model — Reimbursement strategy, hospital sales, or B2C.",
        "Market Analysis — Patient population size and disease prevalence.",
        "Competition — Current standard of care vs. your innovation.",
        "Intellectual Property — Patents and defensive moat.",
        "Traction — Clinical results, pilots, or partnerships with health systems.",
        "Team — Medical expertise, scientific advisors, and business leadership.",
        "Funding & Milestones — Capital needed for trials or commercial launch."
    ],
    "finance": [
        "Cover slide — Brand name and financial tagline.",
        "The Financial Friction — Market inefficiency or user pain point in finance.",
        "Solution — Your fintech product and how it solves the friction.",
        "Key Features — Security, compliance, and user experience.",
        "Market Opportunity — Total Addressable Market in financial services.",
        "Business Model — Transaction fees, interest, or SaaS revenue.",
        "Compliance & Licensing — Regulatory status and risk management.",
        "Traction — User growth, transaction volume, or assets under management.",
        "Competition — Incumbents (Banks) vs. Challenger (You).",
        "Roadmap — Product expansion and geographical rollout.",
        "Team — Financial industry veterans and tech experts.",
        "Funding Ask — Capital for growth, licensing, or operations."
    ],
    "creative_agency": [
        "Cover slide — Agency name and creative manifesto.",
        "The Creative Gap — Why current brand communications are failing.",
        "Philosophy — Your unique creative approach or methodology.",
        "Services — What you offer (Branding, Digital, Production, etc.).",
        "Case Studies — Deep dive into 2-3 successful projects.",
        "Our Portfolio — Visual showcase of diverse work.",
        "Process — How you collaborate with clients from brief to delivery.",
        "Team — The creative minds and strategists behind the work.",
        "Client Testimonials — Social proof from satisfied brands.",
        "Engagement Models — How to work with us (Retainer, Project-based).",
        "Call to Action — Contact details and next steps."
    ],
    "ecommerce": [
        "Cover slide — Brand name and e-commerce tagline.",
        "Market Trend — The shift in consumer behavior and industry growth.",
        "Consumer Pain Point — What's missing in the current shopping experience.",
        "The Product — Brand story, quality, and unique selling points.",
        "Supply Chain — Sourcing, manufacturing, and fulfillment efficiency.",
        "Marketing Strategy — Customer acquisition channels (Social, SEO, Email).",
        "Business Model — Unit economics (AOV, LTV, CAC, Margins).",
        "Traction — Revenue growth, order volume, and repeat customer rate.",
        "Competition — Other brands and your differentiation.",
        "Team — Retail, marketing, and operations experience.",
        "Roadmap — New product lines and international expansion.",
        "Funding Ask — Investment for inventory and marketing scale."
    ],
    "education": [
        "Cover slide — EdTech brand and mission statement.",
        "The Learning Gap — Problem in traditional education or skill building.",
        "Solution — Your platform, content, or tool and its core features.",
        "Pedagogy — The educational science or methodology that makes it work.",
        "Market Opportunity — Student demographics or institutional reach.",
        "Business Model — Subscription, institutional licensing, or freemium.",
        "Traction — Learner engagement, completion rates, or school pilots.",
        "Efficacy — Evidence of improved learning outcomes.",
        "Competition — Existing EdTech players and traditional methods.",
        "Team — Educators, curriculum designers, and software engineers.",
        "Roadmap — Content expansion and platform features.",
        "Funding Ask — Capital for R&D and market expansion."
    ],
    "real_estate": [
        "Cover slide — Brand name and real estate vision.",
        "Market Inefficiency — Problems in property buying, selling, or management.",
        "Solution — Your PropTech solution or real estate innovation.",
        "Market Opportunity — Real estate transaction volume and market size.",
        "Technology — The data, AI, or platform powering the solution.",
        "Business Model — Commissions, SaaS fees, or data licensing.",
        "Traction — Number of listings, users, or successful transactions.",
        "Inventory — Current property portfolio or partnership network.",
        "Competition — Traditional brokers and other PropTech platforms.",
        "Team — Real estate expertise and technology leadership.",
        "Roadmap — Market entry into new cities or asset classes.",
        "Funding Ask — Investment for technology and sales growth."
    ],
    "food_beverage": [
        "Cover slide — Brand name and appetizing tagline.",
        "Consumer Trend — Changing tastes (Healthy, Vegan, Artisanal, etc.).",
        "The Product — Ingredients, taste profile, and packaging.",
        "Target Consumer — Demographic and psychographic profile.",
        "Distribution — Retail presence, food service, and D2C strategy.",
        "Production — Manufacturing capacity and scalability.",
        "Business Model — COGS, margins, and wholesale vs. retail pricing.",
        "Traction — Sales growth, store velocity, and brand awareness.",
        "Competition — Major brands and niche competitors.",
        "Team — Culinary experts, food scientists, and FMCG veterans.",
        "Roadmap — New flavors, product lines, and distribution expansion.",
        "Funding Ask — Capital for production and marketing."
    ],
    "saas_b2b": [
        "Cover slide — SaaS brand and value proposition.",
        "Workflow Inefficiency — The specific B2B problem being solved.",
        "Solution — Software overview and key modules.",
        "Product Demo — Screenshots or walkthrough of core functionality.",
        "Market Opportunity — Enterprise/SMB market size and growth.",
        "Business Model — Tiered subscription pricing and expansion revenue.",
        "Go-to-Market — Sales strategy (Direct, Channel, Product-Led).",
        "Traction — MRR, ARR, churn rate, and key logos.",
        "Customer Success — Testimonials or ROI case studies.",
        "Competition — Legacy systems and modern competitors.",
        "Team — SaaS founders and enterprise sales leaders.",
        "Funding Ask — Capital for engineering and sales hiring."
    ],
    "sustainability": [
        "Cover slide — Brand name and environmental mission.",
        "Environmental Crisis — The specific climate or sustainability problem.",
        "Solution — Your GreenTech innovation and how it works.",
        "Impact Metrics — Projected CO2 reduction, water saved, or waste diverted.",
        "Market & Policy — Regulatory tailwinds and carbon market opportunity.",
        "Business Model — How the solution generates revenue while doing good.",
        "Technology — The science or engineering behind the impact.",
        "Traction — Pilots, government grants, or corporate partnerships.",
        "Competition — Traditional industries vs. sustainable alternatives.",
        "Team — Scientists, engineers, and impact-driven leaders.",
        "Roadmap — Scale-up plan and impact milestones.",
        "Funding Ask — Investment for R&D and commercialization."
    ],
    "fashion_luxury": [
        "Cover slide — Fashion brand and aesthetic vision.",
        "Brand Aesthetic — Visual mood board and brand DNA.",
        "The Consumer — The lifestyle and aspirations of your target buyer.",
        "The Collection — Key products, materials, and design excellence.",
        "Positioning — Exclusivity and price point strategy.",
        "Distribution — Flagship stores, luxury retail partners, and online.",
        "Marketing — Brand storytelling, influencers, and high-fashion PR.",
        "Financials — Gross margins, sell-through rates, and growth.",
        "Sustainability — Ethical sourcing and production practices.",
        "Team — Designers, creative directors, and luxury executives.",
        "Roadmap — Seasonal launches and brand extensions.",
        "Funding Ask — Capital for production, retail, and branding."
    ],
    "sports_fitness": [
        "Cover slide — Brand name and energetic tagline.",
        "Health/Performance Goal — The problem in fitness or athletic performance.",
        "Solution — Your app, wearable, equipment, or fitness concept.",
        "Community — Engagement, social features, and user motivation.",
        "Science & Tech — The data or physiological principles behind it.",
        "Market Opportunity — Fitness industry trends and audience size.",
        "Business Model — Subscriptions, equipment sales, or gym memberships.",
        "Traction — Active users, retention rate, and user transformation stories.",
        "Competition — Major fitness brands and digital alternatives.",
        "Team — Athletes, fitness experts, and technology developers.",
        "Roadmap — New features, hardware, or location expansion.",
        "Funding Ask — Capital for user acquisition and product development."
    ]
}

def get_template(theme_id: str) -> list[str]:
    return DOMAIN_TEMPLATES.get(theme_id, DOMAIN_TEMPLATES["tech_startup"])
